src/post/urls.py
from django.urls import path
from . import views


app_name = 'post'


urlpatterns = [
    path('', views.AllPost , name='post_details'),
    path('<int:id>/', views.PostDetail , name='post_details' ),

]

src/project/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('post.urls') , name = 'post')
]

src/post/models.py
from django.db import models

from django.contrib.auth.models import User

# from django.utils import timezone



# Create your models here.

class Post(models.Model):

    class POSTTYPE_CHOICES(models.TextChoices):
        Question = 'question','سؤال'
        POST = 'post','منشور'
        ARTICLE = 'article','مقال'

    class Status(models.TextChoices):
        DRAFT = 'DF','Draft'
        PUBLISHED = 'PB','published'
    
    type_post = models.CharField( max_length=10 , choices = POSTTYPE_CHOICES.choices,default=POSTTYPE_CHOICES.POST , verbose_name = "نوع المنشور")
    title_post = models.CharField(max_length=250, verbose_name = "عنوان المنشور")
    slug_post = models.SlugField(max_length=250,verbose_name= "اللينك", unique='True')
    author = models.ForeignKey(User, verbose_name="صاحب المنشور", on_delete=models.CASCADE)
    body = models.TextField(max_length=500 , verbose_name="محتوي المنشور")   

    status = models.CharField(max_length=2 , choices = Status.choices,default=Status.DRAFT,verbose_name='حالة المنشور')


    class Meta():
        verbose_name = "منشور"
        verbose_name_plural = "منشورات" 
        # ordering = ['-publish']
        # indexes = [
        #     models.Index(fields=['-publish']),
        # ]


    def __str__(self):
        return self.title_post

src/post/views.py
from django.shortcuts import render
from .models import Post
# Create your views here.


def AllPost(request):
    posts = Post.objects.all()
    # context = {
    #     'post' : posts
    # }
    return render(request,'post/allPost.html',{'posts':posts})

def PostDetail(request,id):

    post = get_object_or_404(Post,status=Post.Status.PUBLISHED,id=Post.id)
    return render(request,'post/PostDetail.html',{'post':post})

src/post/templates/post/PostDetail.html
{% extends "base.html" %}


{% block title %}
    Detail post
{% endblock %}

{% block content %}
    {{post.title_post}}        <br>
    {{post.body}}        <br>

    {{post.author}} <br>
    
{% endblock %}

src/post/templates/post/allPost.html
{% extends "base.html" %}


{% block title %}
    Django Project
{% endblock %}

{% block content %}
    {% for post in posts %}
        <h2>
            <a href='{% url "post:post_details" post.id%} '> {{post.title_post}} </a>
        </h2> 
        {{post.id}}
        <br>
        {{post.body}}        <br>

        {{post.status}}
    {% endfor %}
{% endblock %}

src/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

  {% block content %}
  {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


  </body>
</html>